roadColors = makesymbolspec('Line',...
 {'CLASS', 1, 'Color', 'r'}, ...
 {'CLASS', 2, 'Color', 'g'}, ...
 {'CLASS', 3, 'Color', 'm'},...
 {'CLASS', 4, 'Color', 'b'}, ...
 {'CLASS', 5, 'Color', 'k'}, ...
 {'CLASS', 6, 'Color', 'y'},...
 {'CLASS', 7, 'Color', 'c'});
figure
mapshow('boston_roads.shp', 'SymbolSpec', roadColors);

